- name: This is a hello-world example
  gather_facts: true
  hosts: all
  tasks:
    - name: Create a file called '/tmp/helloworld.txt' with the content 'HELLO WORLD'.
      copy:
        content: HELLO WORLD
        dest: /tmp/helloworld.txt
