- name: This is a hello-world example
  hosts: localhost
  tasks:
    - name: Create a file called '/tmp/helloworld.txt' with the content 'HELLO WORLD'.
      copy:
        content: HELLO WORLD
        dest: /tmp/helloworld.txt
